### ISSUE TITLE
Please update peerDependencies

### ISSUE THREAD

**Issue by ekristen** [deoxxa/docker-events#1]
dockerode is on version 2.0.3, can you please upgrade yours accordingly. Thanks!

**Comment by deoxxa** [comment]
I've actually got no idea if this works, but I've YOLO'd it anyway! Hooray! I'm also going to add you as a maintainer, because I'm going to forget to do this again in the future as I'm barely using this anymore.

**Comment by deoxxa** [comment]
I've also gone ahead and added you as an owner on NPM. Feel free to make releases as you wish!
